### PR TITLE
Parallel strategy

### PR DESCRIPTION
**Pull request by paweljw**

### CODE REVIEW

**Comment by paweljw** [comment]
[Batching endpoint](https://trello.com/c/Xdrve9My/308-batching-endpoint)

**Review by michalg- — APPROVED** [review]

**Comment by kukicola** [comment]
I'm a bit late to the party but I have a question - are you sure it should be handled in processes instead of threads (or even ractors)? In our current heroku setup I wouldn't expect a performance boost with processes (since we have one shared CPU core) and it can result in higher memory usage (we already have some problems with it)

**Comment by paweljw** [comment]
@kukicola fair point, I derped up. I'll leave the API as is, but update `Parallel.map` to use threads instead. Ractors have some extra considerations which I honestly cannot be arsed to work through right now

**Comment by kukicola** [comment]
@paweljw Another idea - instead of spawning threads maybe we should increase the number of puma threads and reuse them here. It would save us from a situation where there are N batch requests with M threads inside, creating N + N*M threads and the same amount of DB connections. It wouldn't be so generic anymore (it wouldn't work with another web server) but at least we wouldn't have to worry about the connection pool or massive load peaks. Wdyt?

**Comment by paweljw** [comment]
I see where you're coming from, but I don't think I have a clue how such an implementation would look like. Drop me a hint? :D

**Comment by kukicola** [comment]
I have no clue either :D , I will take a look at it tomorrow on workshops

**Comment by paweljw** [comment]
@kukicola on Friday*. Someone's been messing with your calendar again

**Pull request merged**
